This is makeindex, version 2.17 [TeX Live 2024] (kpathsea + Thai support).
Scanning style file ./bp.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file bp.acn....done (4 entries accepted, 0 rejected).
Sorting entries....done (9 comparisons).
Generating output file bp.acr....done (15 lines written, 0 warnings).
Output written in bp.acr.
Transcript written in bp.alg.
