name: Build LaTeX document
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: bp.tex
          latexmk_use_lualatex: true

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: bp-pdf
          path: bp.pdf

  deploy:
                name: Deploy
                needs: build
                runs-on: ubuntu-latest
                steps:
                  - name: Download artifact
                    uses: actions/download-artifact@v4
                    with:
                      name: bp-pdf
                      path: bp.pdf
                  - name: 📂 Upload files
                    uses: SamKirkland/FTP-Deploy-Action@4.2.0
                    with:
                      server: andrejvysny.sk
                      username: get.marekgavura.sk
                      password: ${{ secrets.FTP_PASS }}